### ISSUE TITLE
Recieve data (to the Android App) from the C server

### ISSUE THREAD

**Issue by bistanur** [zakuArbor/proxyAuth#16]
Make sure the Android app is able to receive messages from the C server application

**Comment by zakuArbor** [comment]
I have pulled the latest code from the `master` branch and was testing on the status of this issue. There does not seem to be any issues on the `server` (`deauth` program) nor reading from the Android device. This issue has been completed by `4dc03d772e6d5a4ac2c100faec16742f81184fbd`. However, there is a problem with the implementation of read. 

Since the implementation has placed read to an infinite loop, I cannot even send writes to the server manually. We want the server to communicate back and forth so there needs to  be more work done on this issue.
```
while (true) {
                // Read from the InputStream.
                //numBytes =
                try {
                    numBytes = m_bluetoothSocket!!.inputStream.read(mmBuffer)
```

**Comment by zakuArbor** [comment]
Another issue with this implementation is that when I look at the logcat on Android Studio, I can see that the app will not read any messages from the server till one write occurs.
